# Generated by Django 2.0.6 on 2018-06-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('device_ip', models.CharField(max_length=30)),
                ('device_code', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
