# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=30)),
                ('set_company', models.CharField(max_length=30)),
                ('set_manager', models.CharField(max_length=30)),
            ],
        ),
    ]
