# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_set_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='device_info',
            new_name='Deviceinfo',
        ),
        migrations.RenameModel(
            old_name='set_info',
            new_name='Setinfo',
        ),
    ]
