# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180718_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='set_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
